# -*- coding: utf-8 -*-
# ==========================================
# Generated by Borno Compiler
# Target: Python 3 (Generated from TAC)
# ==========================================

import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

বয়স = 20
নাম = "মাহদি"
t1 = বয়স >= 18
if t1:
    অবস্থা = 1
else:
    অবস্থা = 0
