;; ==========================================
;; Generated by Borno Compiler
;; Target: WebAssembly Text Format (.wat)
;; ==========================================
(module
  ;; Host environment helper imports
  (import "env" "print_i32" (func $print_i32 (param i32)))
  (import "env" "print_str" (func $print_str (param i32 i32)))

  ;; Memory export (1 page = 64KB)
  (memory (export "memory") 1)

  ;; Data segments for string literals
  (data (i32.const 0) "মাহদি\00")

  (func $main (export "main")
    ;; Local variables
    (local $var_0 i32)  ;; বয়স
    (local $var_1 i32)  ;; নাম
    (local $var_2 i32)  ;; অবস্থা

    ;; বয়স = ...
    i32.const 20
    local.set $var_0
    ;; নাম = ...
    i32.const 0  ;; string ptr
    local.set $var_1
    ;; যদি (condition)
    local.get $var_0
    i32.const 18
    i32.ge_s
    if
      ;; অবস্থা = ...
      i32.const 1
      local.set $var_2
    else
      ;; অবস্থা = ...
      i32.const 0
      local.set $var_2
    end
  )
)
