package codegen;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import tac.TACInstruction;
import tac.TACProgram;
import token.NumberHelper;

/**
 * PythonGenerator — Translates Three Address Code (TAC) into executable Python 3 target code.
 *
 * Architecture:
 * Source Code → Lexer → Parser → AST → Semantic Analysis → TAC Generator → TAC Program → PythonGenerator
 */
public class PythonGenerator {

    /**
     * Generates Python 3 source code from a TACProgram.
     *
     * @param tacProgram The Three Address Code program to translate.
     * @return Formatted, syntactically valid Python 3 source code.
     */
    public String generate(TACProgram tacProgram) {
        StringBuilder sb = new StringBuilder();
        sb.append("# -*- coding: utf-8 -*-\n");
        sb.append("# ==========================================\n");
        sb.append("# Generated by Borno Compiler\n");
        sb.append("# Target: Python 3 (Generated from TAC)\n");
        sb.append("# ==========================================\n\n");
        sb.append("import sys\n");
        sb.append("if hasattr(sys.stdout, 'reconfigure'):\n");
        sb.append("    sys.stdout.reconfigure(encoding='utf-8')\n\n");

        if (tacProgram == null || tacProgram.isEmpty()) {
            sb.append("pass\n");
            return sb.toString();
        }

        List<TACInstruction> instructions = tacProgram.getInstructions();
        generateBlock(instructions, 0, instructions.size(), sb, 0);

        String result = sb.toString();
        if (result.trim().endsWith("# ==========================================")) {
            sb.append("pass\n");
            return sb.toString();
        }

        return result;
    }

    /**
     * Overloaded method to generate Python 3 source code directly from a list of TAC instructions.
     *
     * @param instructions The list of TAC instructions.
     * @return Formatted Python 3 source code.
     */
    public String generate(List<TACInstruction> instructions) {
        TACProgram tac = new TACProgram();
        if (instructions != null) {
            for (TACInstruction inst : instructions) {
                tac.add(inst);
            }
        }
        return generate(tac);
    }

    /**
     * Recursively translates a slice of TAC instructions into a block with proper indentation.
     */
    private int generateBlock(List<TACInstruction> instructions, int start, int end, StringBuilder sb, int level) {
        String ind = "    ".repeat(level);
        int i = start;

        while (i < end) {
            TACInstruction inst = instructions.get(i);
            TACInstruction.OpType opType = inst.getOpType();

            switch (opType) {
                case ASSIGN_BINARY -> {
                    String res = inst.getResult();
                    String op1 = formatOperand(inst.getArg1());
                    String op = translateOperator(inst.getOp());
                    String op2 = formatOperand(inst.getArg2());
                    sb.append(ind)
                      .append(res)
                      .append(" = ")
                      .append(op1)
                      .append(" ")
                      .append(op)
                      .append(" ")
                      .append(op2)
                      .append("\n");
                    i++;
                }
                case ASSIGN_UNARY -> {
                    String res = inst.getResult();
                    String op = translateOperator(inst.getOp());
                    String op1 = formatOperand(inst.getArg1());
                    sb.append(ind)
                      .append(res)
                      .append(" = ")
                      .append(op)
                      .append(op1)
                      .append("\n");
                    i++;
                }
                case ASSIGN_COPY -> {
                    String res = inst.getResult();
                    String op1 = formatOperand(inst.getArg1());
                    sb.append(ind)
                      .append(res)
                      .append(" = ")
                      .append(op1)
                      .append("\n");
                    i++;
                }
                case PRINT -> {
                    String val = formatPrintArg(inst.getArg1());
                    sb.append(ind)
                      .append("print(")
                      .append(val)
                      .append(")\n");
                    i++;
                }
                case IF_FALSE_GOTO -> {
                    String cond = formatOperand(inst.getArg1());
                    String targetLabel = inst.getResult();

                    int targetIndex = findLabelIndex(instructions, i + 1, end, targetLabel);
                    if (targetIndex != -1) {
                        // Check if immediately before targetLabel there is a GOTO (if-else pattern)
                        if (targetIndex > i + 1 && instructions.get(targetIndex - 1).getOpType() == TACInstruction.OpType.GOTO) {
                            String endLabel = instructions.get(targetIndex - 1).getResult();
                            int endIndex = findLabelIndex(instructions, targetIndex + 1, end, endLabel);

                            if (endIndex != -1) {
                                // Structured IF-ELSE construct
                                sb.append(ind).append("if ").append(cond).append(":\n");
                                if (i + 1 == targetIndex - 1) {
                                    sb.append(ind).append("    pass\n");
                                } else {
                                    generateBlock(instructions, i + 1, targetIndex - 1, sb, level + 1);
                                }

                                sb.append(ind).append("else:\n");
                                if (targetIndex + 1 == endIndex) {
                                    sb.append(ind).append("    pass\n");
                                } else {
                                    generateBlock(instructions, targetIndex + 1, endIndex, sb, level + 1);
                                }

                                i = endIndex + 1;
                                break;
                            }
                        }

                        // Structured IF construct (without else)
                        sb.append(ind).append("if ").append(cond).append(":\n");
                        if (i + 1 == targetIndex) {
                            sb.append(ind).append("    pass\n");
                        } else {
                            generateBlock(instructions, i + 1, targetIndex, sb, level + 1);
                        }

                        i = targetIndex + 1;
                    } else {
                        // Standalone conditional jump
                        sb.append(ind).append("if not (").append(cond).append("):\n");
                        sb.append(ind).append("    # goto ").append(targetLabel).append("\n");
                        sb.append(ind).append("    pass\n");
                        i++;
                    }
                }
                case IF_GOTO -> {
                    String cond = formatOperand(inst.getArg1());
                    String targetLabel = inst.getResult();
                    sb.append(ind).append("if ").append(cond).append(":\n");
                    sb.append(ind).append("    # goto ").append(targetLabel).append("\n");
                    sb.append(ind).append("    pass\n");
                    i++;
                }
                case GOTO -> {
                    sb.append(ind).append("# goto ").append(inst.getResult()).append("\n");
                    i++;
                }
                case LABEL -> {
                    sb.append(ind).append("# Label: ").append(inst.getResult()).append("\n");
                    i++;
                }
                default -> i++;
            }
        }

        return i;
    }

    /**
     * Finds the index of a LABEL instruction matching the target name in the given range.
     */
    private int findLabelIndex(List<TACInstruction> instructions, int start, int end, String labelName) {
        if (labelName == null) return -1;
        for (int j = start; j < end; j++) {
            TACInstruction inst = instructions.get(j);
            if (inst.getOpType() == TACInstruction.OpType.LABEL && labelName.equals(inst.getResult())) {
                return j;
            }
        }
        return -1;
    }

    /**
     * Formats an operand for Python syntax (converts Bangla numbers, preserves strings & identifiers).
     */
    private String formatOperand(String op) {
        if (op == null) return "None";
        String trimmed = op.trim();

        if (NumberHelper.isNumber(trimmed)) {
            return NumberHelper.toAsciiDigits(trimmed);
        }

        if (trimmed.startsWith("\"") && trimmed.endsWith("\"")) {
            return trimmed;
        }

        return trimmed;
    }

    /**
     * Formats argument for print statements, handling legacy দেখাও(...) format if present.
     */
    private String formatPrintArg(String arg) {
        if (arg == null) return "";
        String trimmed = arg.trim();
        if (trimmed.startsWith("দেখাও(") && trimmed.endsWith(")")) {
            trimmed = trimmed.substring(6, trimmed.length() - 1).trim();
        }
        return formatOperand(trimmed);
    }

    /**
     * Translates Borno/Bangla operators into standard Python equivalents.
     */
    private String translateOperator(String op) {
        if (op == null) return "";
        return switch (op) {
            case "এবং", "&&" -> "and";
            case "অথবা", "||" -> "or";
            case "না", "!" -> "not ";
            default -> op;
        };
    }

    /**
     * Writes the generated Python code to a file.
     */
    public static File writeToFile(String pythonCode, String filePath) throws IOException {
        Path path = Path.of(filePath);
        if (path.getParent() != null) {
            Files.createDirectories(path.getParent());
        }
        Files.writeString(path, pythonCode, StandardCharsets.UTF_8);
        return path.toFile();
    }
}
