package codegen;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

import ast.*;
import token.NumberHelper;

/**
 * WasmGenerator — Translates Borno AST into standard WebAssembly Text Format (.wat).
 */
public class WasmGenerator {

    private final Map<String, String> varToLocal = new LinkedHashMap<>();
    private final Map<String, Integer> stringOffsets = new LinkedHashMap<>();
    private final Map<String, Integer> stringLengths = new LinkedHashMap<>();
    private int currentMemoryOffset = 0;

    public static class WasmResult {
        public final String watCode;
        public final boolean wasmCompiled;
        public final String statusMessage;

        public WasmResult(String watCode, boolean wasmCompiled, String statusMessage) {
            this.watCode = watCode;
            this.wasmCompiled = wasmCompiled;
            this.statusMessage = statusMessage;
        }
    }

    public String generate(ProgramNode program) {
        varToLocal.clear();
        stringOffsets.clear();
        stringLengths.clear();
        currentMemoryOffset = 0;

        // 1. Scan for variables and string literals
        scanProgram(program);

        StringBuilder sb = new StringBuilder();
        sb.append(";; ==========================================\n");
        sb.append(";; Generated by Borno Compiler\n");
        sb.append(";; Target: WebAssembly Text Format (.wat)\n");
        sb.append(";; ==========================================\n");
        sb.append("(module\n");

        // Imports
        sb.append("  ;; Host environment helper imports\n");
        sb.append("  (import \"env\" \"print_i32\" (func $print_i32 (param i32)))\n");
        sb.append("  (import \"env\" \"print_str\" (func $print_str (param i32 i32)))\n\n");

        // Memory
        sb.append("  ;; Memory export (1 page = 64KB)\n");
        sb.append("  (memory (export \"memory\") 1)\n\n");

        // Data segments for strings
        if (!stringOffsets.isEmpty()) {
            sb.append("  ;; Data segments for string literals\n");
            for (Map.Entry<String, Integer> entry : stringOffsets.entrySet()) {
                String raw = entry.getKey();
                int offset = entry.getValue();
                String escaped = raw.replace("\\", "\\\\").replace("\"", "\\\"");
                sb.append("  (data (i32.const ").append(offset).append(") \"").append(escaped).append("\\00\")\n");
            }
            sb.append("\n");
        }

        // Main function
        sb.append("  (func $main (export \"main\")\n");

        // Local variable declarations
        if (!varToLocal.isEmpty()) {
            sb.append("    ;; Local variables\n");
            for (Map.Entry<String, String> entry : varToLocal.entrySet()) {
                sb.append("    (local ").append(entry.getValue()).append(" i32)  ;; ").append(entry.getKey()).append("\n");
            }
            sb.append("\n");
        }

        // Statements
        if (program != null) {
            for (ASTNode stmt : program.getStatements()) {
                generateStatement(stmt, sb, 2);
            }
        }

        sb.append("  )\n");
        sb.append(")\n");

        return sb.toString();
    }

    private void scanProgram(ProgramNode program) {
        if (program == null) return;
        for (ASTNode stmt : program.getStatements()) {
            scanNode(stmt);
        }
    }

    private void scanNode(ASTNode node) {
        if (node instanceof AssignmentNode) {
            AssignmentNode assign = (AssignmentNode) node;
            if (!varToLocal.containsKey(assign.getVariableName())) {
                String localName = "$var_" + varToLocal.size();
                varToLocal.put(assign.getVariableName(), localName);
            }
            scanNode(assign.getExpression());
        } else if (node instanceof PrintNode) {
            scanNode(((PrintNode) node).getExpression());
        } else if (node instanceof IfNode) {
            IfNode ifNode = (IfNode) node;
            scanNode(ifNode.getCondition());
            if (ifNode.getThenBranch() != null) {
                for (ASTNode s : ifNode.getThenBranch()) scanNode(s);
            }
            if (ifNode.getElseBranch() != null) {
                for (ASTNode s : ifNode.getElseBranch()) scanNode(s);
            }
        } else if (node instanceof BlockNode) {
            for (ASTNode s : ((BlockNode) node).getStatements()) scanNode(s);
        } else if (node instanceof BinaryExpressionNode) {
            BinaryExpressionNode bin = (BinaryExpressionNode) node;
            scanNode(bin.getLeft());
            scanNode(bin.getRight());
        } else if (node instanceof LiteralNode) {
            String val = ((LiteralNode) node).getValue();
            if (!NumberHelper.isNumber(val)) {
                String clean = val;
                if (clean.startsWith("\"") && clean.endsWith("\"") && clean.length() >= 2) {
                    clean = clean.substring(1, clean.length() - 1);
                }
                if (!stringOffsets.containsKey(clean)) {
                    byte[] bytes = clean.getBytes(StandardCharsets.UTF_8);
                    stringOffsets.put(clean, currentMemoryOffset);
                    stringLengths.put(clean, bytes.length);
                    currentMemoryOffset += bytes.length + 1; // null-terminated
                }
            }
        }
    }

    private void generateStatement(ASTNode node, StringBuilder sb, int level) {
        String ind = "  ".repeat(level);

        if (node instanceof AssignmentNode) {
            AssignmentNode assign = (AssignmentNode) node;
            String local = varToLocal.get(assign.getVariableName());
            sb.append(ind).append(";; ").append(assign.getVariableName()).append(" = ...\n");
            generateExpression(assign.getExpression(), sb, level);
            sb.append(ind).append("local.set ").append(local).append("\n");

        } else if (node instanceof PrintNode) {
            PrintNode print = (PrintNode) node;
            ASTNode expr = print.getExpression();
            sb.append(ind).append(";; দেখাও(...)\n");

            if (isStringExpression(expr)) {
                // String print
                generateStringExpression(expr, sb, level);
                sb.append(ind).append("call $print_str\n");
            } else {
                // Numeric print
                generateExpression(expr, sb, level);
                sb.append(ind).append("call $print_i32\n");
            }

        } else if (node instanceof IfNode) {
            IfNode ifNode = (IfNode) node;
            sb.append(ind).append(";; যদি (condition)\n");
            generateExpression(ifNode.getCondition(), sb, level);
            sb.append(ind).append("if\n");

            List<ASTNode> thenBranch = ifNode.getThenBranch();
            if (thenBranch != null) {
                for (ASTNode s : thenBranch) {
                    generateStatement(s, sb, level + 1);
                }
            }

            if (ifNode.hasElse()) {
                sb.append(ind).append("else\n");
                List<ASTNode> elseBranch = ifNode.getElseBranch();
                if (elseBranch != null) {
                    for (ASTNode s : elseBranch) {
                        generateStatement(s, sb, level + 1);
                    }
                }
            }

            sb.append(ind).append("end\n");

        } else if (node instanceof BlockNode) {
            BlockNode block = (BlockNode) node;
            for (ASTNode s : block.getStatements()) {
                generateStatement(s, sb, level);
            }
        }
    }

    private boolean isStringExpression(ASTNode node) {
        if (node instanceof LiteralNode) {
            return !NumberHelper.isNumber(((LiteralNode) node).getValue());
        }
        return false;
    }

    private void generateStringExpression(ASTNode node, StringBuilder sb, int level) {
        String ind = "  ".repeat(level);
        if (node instanceof LiteralNode) {
            String val = ((LiteralNode) node).getValue();
            String clean = val;
            if (clean.startsWith("\"") && clean.endsWith("\"") && clean.length() >= 2) {
                clean = clean.substring(1, clean.length() - 1);
            }
            int offset = stringOffsets.getOrDefault(clean, 0);
            int len = stringLengths.getOrDefault(clean, 0);
            sb.append(ind).append("i32.const ").append(offset).append("  ;; string offset\n");
            sb.append(ind).append("i32.const ").append(len).append("  ;; string length\n");
        } else {
            sb.append(ind).append("i32.const 0\n");
            sb.append(ind).append("i32.const 0\n");
        }
    }

    private void generateExpression(ASTNode node, StringBuilder sb, int level) {
        String ind = "  ".repeat(level);

        if (node instanceof LiteralNode) {
            String val = ((LiteralNode) node).getValue();
            if (NumberHelper.isNumber(val)) {
                String ascii = NumberHelper.toAsciiDigits(val);
                int intVal = (int) Double.parseDouble(ascii);
                sb.append(ind).append("i32.const ").append(intVal).append("\n");
            } else {
                String clean = val;
                if (clean.startsWith("\"") && clean.endsWith("\"") && clean.length() >= 2) {
                    clean = clean.substring(1, clean.length() - 1);
                }
                int offset = stringOffsets.getOrDefault(clean, 0);
                sb.append(ind).append("i32.const ").append(offset).append("  ;; string ptr\n");
            }

        } else if (node instanceof VariableNode) {
            String name = ((VariableNode) node).getName();
            String local = varToLocal.get(name);
            if (local != null) {
                sb.append(ind).append("local.get ").append(local).append("\n");
            } else {
                sb.append(ind).append("i32.const 0\n");
            }

        } else if (node instanceof BinaryExpressionNode) {
            BinaryExpressionNode bin = (BinaryExpressionNode) node;
            generateExpression(bin.getLeft(), sb, level);
            generateExpression(bin.getRight(), sb, level);

            switch (bin.getOperator()) {
                case "+":
                    sb.append(ind).append("i32.add\n");
                    break;
                case "-":
                    sb.append(ind).append("i32.sub\n");
                    break;
                case "*":
                    sb.append(ind).append("i32.mul\n");
                    break;
                case "/":
                    sb.append(ind).append("i32.div_s\n");
                    break;
                case "%":
                    sb.append(ind).append("i32.rem_s\n");
                    break;
                case "==":
                    sb.append(ind).append("i32.eq\n");
                    break;
                case "!=":
                    sb.append(ind).append("i32.ne\n");
                    break;
                case "<":
                    sb.append(ind).append("i32.lt_s\n");
                    break;
                case ">":
                    sb.append(ind).append("i32.gt_s\n");
                    break;
                case "<=":
                    sb.append(ind).append("i32.le_s\n");
                    break;
                case ">=":
                    sb.append(ind).append("i32.ge_s\n");
                    break;
                default:
                    sb.append(ind).append(";; unknown operator: ").append(bin.getOperator()).append("\n");
                    break;
            }
        }
    }

    public static File writeToFile(String watCode, String filePath) throws IOException {
        Path path = Path.of(filePath);
        if (path.getParent() != null) {
            Files.createDirectories(path.getParent());
        }
        Files.writeString(path, watCode, StandardCharsets.UTF_8);
        return path.toFile();
    }

    /**
     * Attempts to compile .wat to .wasm using external wat2wasm tool if available.
     * Does NOT fail or throw if wat2wasm is not installed.
     */
    public static boolean compileWatToWasm(String watFilePath, String wasmFilePath) {
        try {
            ProcessBuilder pb = new ProcessBuilder("wat2wasm", watFilePath, "-o", wasmFilePath);
            pb.redirectErrorStream(true);
            Process process = pb.start();
            int exitCode = process.waitFor();
            return exitCode == 0;
        } catch (Exception e) {
            // wat2wasm not found or error occurred — graceful fallback
            return false;
        }
    }
}
